# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"
# notifier = "i3nag"

[theme]
name = "semi-native" # semi-native nord-dark
[theme.overrides]

[icons]
name = "awesome"
[icons.overrides]

[[block]]
block = "watson"
show_time = true
state_path = "~/.config/watson/state"

[[block]]
block = "music"
buttons = ["play"]
player = "chromium"
max_width = 30
dynamic_width = true
on_collapsed_click = "google-chrome https://music.yandex.ru/"
hide_when_empty = false

[[block]]
block = "music"
buttons = ["play"]
player = "Blanket"
max_width = 30
dynamic_width = true
on_collapsed_click = "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=blanket com.rafaelmardojai.Blanket"

# [[block]]
# block = "disk_space"
# info_type = "available"
# format = "{available} free"

# [[block]]
# block = "net"
# device = "wlp5s0"
# format = "🌐 {ssid}"
# interval = 5

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
chip = "*-isa-*"
format = "{average}, {max}"


[[block]]
block = "sound"
format = "{output_description} {volume}"
icons_format = "{icon}  "
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🎧"

[[block]]
block = "battery"
format = "{percentage} {power}"
critical = 5
warning = 15

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
interval = 1

[[block]]
block = "time"
format = "%a %d %b (%m) %R"
interval = 60
locale = "ru_RU"
timezone = "Europe/Moscow"
